
development:
  adapter: postgresql
  database: FlySpot-Backend_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: FlySpot-Backend_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: FlySpot-Backend_production
  pool: 5
  timeout: 5000









development:
  adapter: postgresql
  encoding: unicode
  database: FlySpot-Backend_development
  pool: 5 
  username: 
  password:
  timeout: 5000


  test:
    adapter: postgresql
    encoding: unicode
    database: FlySpot-Backend_test
    pool: 5
    username:
      password:
        timeout: 5000


