development:
  adapter: postgresql
  encoding: unicode
  database: FlySpot-Backend_development
  pool: 5 
  username: 
  password:
  timeout: 5000


  test:
    adapter: postgresql
    encoding: unicode
    database: Flyspot-Backend_test
    pool: 5
    username:
      password:
        timeout: 5000


